dist: bionic
os: linux
language: shell
services: docker

env:
  global:
    - IMAGE=drpsychick/linuxgsm-ark
  jobs:
    - UBUNTU_VERSION=latest
    - UBUNTU_VERSION=focal
    - UBUNTU_VERSION=eoan
    - UBUNTU_VERSION=bionic

before_script:
  - docker build --pull -t $IMAGE --build-arg UBUNTU_VERSION=$UBUNTU_VERSION .
  - VERSION=$(eval $(docker run --rm --entrypoint grep $IMAGE ^version= linuxgsm.sh); echo $version)

script:
  # test always passes
  - echo "Ubuntu $UBUNTU_VERSION linuxgsm $VERSION"
  - >
    echo "Running container: list servers...";
    docker run --rm --entrypoint ./linuxgsm.sh $IMAGE list

after_success:
  - bash deploy.sh
